//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.19 at 11:34:57 AM MSD 
//


package ru.fors.diagnostics.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}hostName"/>
 *         &lt;element ref="{}port"/>
 *         &lt;element ref="{}contextRoot"/>
 *         &lt;element ref="{}protocol"/>
 *         &lt;element ref="{}authconfig"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hostName",
    "port",
    "contextRoot",
    "protocol",
    "authconfig"
})
@XmlRootElement(name = "server")
public class Server {

    @XmlElement(required = true)
    protected String hostName;
    protected int port;
    @XmlElement(required = true)
    protected String contextRoot;
    @XmlElement(required = true)
    protected String protocol;
    @XmlElement(required = true)
    protected Authconfig authconfig;

    public Server() {   }

    public Server(String protocol,String hostName, int port, String contextRoot) {
        this.hostName = hostName;
        this.port = port;
        this.contextRoot = contextRoot;
        this.protocol = protocol;
        this.authconfig = authconfig;
    }

    /**
     * Gets the value of the hostName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostName() {
        return hostName;
    }

    /**
     * Sets the value of the hostName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostName(String value) {
        this.hostName = value;
    }

    /**
     * Gets the value of the port property.
     * 
     */
    public int getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     */
    public void setPort(int value) {
        this.port = value;
    }

    /**
     * Gets the value of the contextRoot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContextRoot() {
        return contextRoot;
    }

    /**
     * Sets the value of the contextRoot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContextRoot(String value) {
        this.contextRoot = value;
    }

    /**
     * Gets the value of the protocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * Sets the value of the protocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtocol(String value) {
        this.protocol = value;
    }

    /**
     * Gets the value of the authconfig property.
     * 
     * @return
     *     possible object is
     *     {@link Authconfig }
     *     
     */
    public Authconfig getAuthconfig() {
        return authconfig;
    }

    /**
     * Sets the value of the authconfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link Authconfig }
     *     
     */
    public void setAuthconfig(Authconfig value) {
        this.authconfig = value;
    }

}
